### ISSUE TITLE
ImportError when run `python diffusion_itm.py --task flickr30k_text`

### ISSUE THREAD

**Issue by cmhungsteve** [McGill-NLP/diffusion-itm#2]
Hello,

After installing all the packages as mentioned in the README, I met the following error:

``
ImportError: cannot import name 'CpuOffload' from 'accelerate.hooks' (/home/minhungc/anaconda3/envs/diffcap/lib/python3.10/site-packages/accelerate/hooks.py)
``

The packages that I have are as follows (I only list the ones also in `requirements.txt`):
accelerate==0.16.0
datasets==2.10.1
diffusers==0.17.0.dev0
easydict==1.11 
nltk==3.8.1 
pandas==2.1.1
pip==23.3
python==3.10.13
spacy==3.5.2
torch==1.13.0+cu117
torchaudio==0.13.0+cu117
torchvision==0.14.0+cu117
tqdm==4.66.1
transformers==4.26.1

The version numbers are slightly different from `requirements.txt`, but I am not sure if this really matters.

Have you met this issue before?
If so, how did you address this issue?
If not, what are some possible reasons in your opinion?

Thank you so much!

**Comment by BennoKrojer** [comment]
Hi! I do remember that accelerate is sensitive to the versions sometimes so I would advice you to try first installing the exact the versions and then letting me know if it still persists.
Benno

**Comment by cmhungsteve** [comment]
I checked your `requirements.txt` as follows: 
torch==1.13.0
torchvision==0.14.0
transformers==4.26.1
accelerate==0.16.0
datasets==2.10.1
spacy==3.5.2

My package versions are all the same as yours except for two parts:
- my PyTorch is with cuda 11.7, which is not shown in your `requirements.txt`
- I use `diffusers==0.17.0.dev0` which is obtained by directly running `python setup.py install` under `diffusers/`
I am not sure if the above two matters.

Another thing is that I create a new environment and install the libraries in `requirements.txt` first and then install diffusers.
However, the order is different in README (i.e., install diffusers first, and then install libraries in `requirements.txt`)
Does the order of installation matter?

Thank you.

**Comment by cmhungsteve** [comment]
It works if I directly follow the pip installation step from the official huggingface diffusers:
https://huggingface.co/docs/diffusers/installation
`pip install diffusers["torch"] transformers`
It will install `diffusers`, `accelerate`, and `transformers` together, so there won't be any version conflict issue.

[Update] I found that there are still errors running the code since you actually modified diffusers. Still trying.....

**Comment by cmhungsteve** [comment]
[Current status] It's running, finally

If I install `diffuers` by following the official instructions, I meet the following error:
```
Traceback (most recent call last):
  File "/home/minhungc/Projects/diffusion-itm/diffusion_itm.py", line 249, in <module>
    main(args)
  File "/home/minhungc/Projects/diffusion-itm/diffusion_itm.py", line 85, in main
    scores = score_batch(i, args, batch, model)
  File "/home/minhungc/Projects/diffusion-itm/diffusion_itm.py", line 40, in score_batch
    dists = model(prompt=list(text), image=resized_img, guidance_scale=args.guidance_scale, sampling_steps=args.sampling_steps, unconditional=args.img_retrieval)
  File "/home/minhungc/anaconda3/envs/diffcap/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionImg2ImgPipeline.__call__() got an unexpected keyword argument 'sampling_steps'
```
I guess the reason is that you modified the diffuers functions and added some new agreements

But if I install `diffuers` by running `pip install -e ".[torch]"` under the folder `diffusers/`, I get the following error:
```
Traceback (most recent call last):                           
  File "/home/minhungc/Projects/diffusion-itm/diffusion_itm.py", line 249, in <module>                                     
    main(args)                                                                                                             
  File "/home/minhungc/Projects/diffusion-itm/diffusion_itm.py", line 56, in main                                          
    model = StableDiffusionImg2ImgPipeline.from_pretrained(model_id, scheduler=scheduler, torch_dtype=torch.float16)
  File "/home/minhungc/Projects/diffusion-itm/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1101, in from_pret
rained                                                                                                                     
    model = pipeline_class(**init_kwargs)                                                                                  
  File "/home/minhungc/Projects/diffusion-itm/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_
img2img.py", line 232, in __init__                                                                                         
    with open(os.path.expanduser("~/diffusers/noise_samples.pkl"), "wb") as f:                                             
FileNotFoundError: [Errno 2] No such file or directory: '/home/minhungc/diffusers/noise_samples.pkl'                       
```
And I just created a folder `diffusers/` under the user directory, then the code starts running!!

**Comment by BennoKrojer** [comment]
Hi! I can look into this today. But does your very last sentence mean you got it running now?

**Comment by cmhungsteve** [comment]
yeah, I guess running `pip install -e ".[torch]"` instead of `python setup.py install` for installing `diffusers` does help since `pip install -e ".[torch]"` also install `accelerate` at the same time. This would avoid the version conflict issue.

**Comment by yiranxie233** [comment]
Sorry, when I reproduce the zero shot retrieval, I faced the error like you before
~~~python
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/diffusers/noise_samples.pkl'
~~~
and like your advice to create a diffusers directory in usrs, but still do not work, can you give me some advice?
