### ISSUE TITLE
lora checkpoint

### ISSUE THREAD

**Issue by Chao0511** [McGill-NLP/diffusion-itm#4]
Hi,

Thanks for releasing the code.
is it possible to add the Lora checkpoints to the repo?
thanks

**Comment by BennoKrojer** [comment]
Hi! I am trying to find them right now again and will add them to the repo once I am sure it is correct. Thanks for bringing this up. I found some checkpoints but want to make sure it is the ones that produced the numbers in the paper.

Best,
Benno

**Comment by BennoKrojer** [comment]
I added two checkpoints I was able to verify and recover, see the new README section:
https://github.com/McGill-NLP/diffusion-itm?tab=readme-ov-file#fine-tuned-itm

Let me know if you need other checkpoints than this one.

Best,
Benno

**Comment by Chao0511** [comment]
Hi, thanks for the sharing! 
Just double check that, the Lora checkpoint should be loaded on SD v2-1, not SD v2-1-base, correct? 
Thanks again :)

**Comment by BennoKrojer** [comment]
It is 2-1-base! For example as used here: https://github.com/McGill-NLP/diffusion-itm/blob/7d5a9c0bcfd32754f26461a2f8fee73e2f01c7a2/diffusion_itm.py#L54C21-L54C58

**Comment by Chao0511** [comment]
It's clear. Many thanks :)
