### ISSUE TITLE
question about readme's python command

### ISSUE THREAD

**Issue by yiranxie233** [McGill-NLP/diffusion-itm#5]
Thank you for your open-resourced project about the paper diffusion-itm. It is a great work!
I'm a beginner in this area.
When I reproduced the code your released, I feel little confused.  
I think the [first readme python command](https://github.com/McGill-NLP/diffusion-itm/blob/main/README.md?plain=1#L89) refer to the paper's table2‘s vanilla SD result. Because the result after I reproduced is closer to this, am I right?
Is the [second python command](https://github.com/McGill-NLP/diffusion-itm/blob/main/README.md?plain=1#L105) to conduct your proposed hard_diff_itm in table1?
And I notice that in diffusion-itm.py the lora_type in the code, where can I get these different kinds of lora type? 
If you can reply, I will appreciate very much!!

**Comment by BennoKrojer** [comment]
Hi! Thanks a lot for appreciating and and trying to reproduce it! And best of luck getting started with research on this.

Indeed, as the title says "Zero-shot Image-Text-Matching (DiffusionITM)", it is the table1 row "DiffusionITM (Ours)":
<img width="797" alt="image" src="https://github.com/user-attachments/assets/64544784-cbb6-4c0a-95b0-b4fef53a43cc">

And then the next command is for the HardNeg finetuning.

**Comment by BennoKrojer** [comment]
Do you mean "lora_dir"?
You simply pass the directory where the lora weights are, e.g.: https://github.com/McGill-NLP/diffusion-itm/tree/main/checkpoints/hardneg-checkpoint-5000

I hope this resolves it!

**Comment by yiranxie233** [comment]
Hi, thank you for your reply!! Sorry for bother you again. 
1. I use the command
~~~python
python diffusion_itm,py --task flickr30k --seed 42 --subset --img_retrieval
~~~
on RTX4070Ti Super
I think I do not use the hardneg fine-tune on the mscoco ,then got the result like the  table2's first row, so I have the problem. I think the hard_neg fine-tune on the mscoco is to get the lora weight. 
![image](https://github.com/user-attachments/assets/793fc3b1-548c-47a2-a464-52197cc20747)
![image](https://github.com/user-attachments/assets/1a6ef593-9cd6-4a95-8058-a75c5c0ac9c1)
2. And I also want to know about the GPU memory cost when you do the single GPU experiment on hard_neg mscoco fine-tune,  because either I use RTX4070TiSuper or 3090 it told me the CUDA out of memory.
